apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app
  labels:
    app: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
        - name: finance
          image: 562887204706.dkr.ecr.us-east-1.amazonaws.com/financecs330:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: finance-secrets
